# Generated by Django 2.2.19 on 2021-03-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chat', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('pregunta', models.CharField(max_length=450)),
                ('respuesta', models.CharField(max_length=20)),
            ],
        ),
    ]
